backend:
  name: github
  repo: jornadablue/jornadablue.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "buttons"
    label: "Botões da Página Principal"
    folder: "data/buttons" # Mudei de _data para data, mais seguro.
    create: true
    slug: "{{slug}}" # Nome do arquivo será baseado no texto do botão
    fields:
      - {label: "Texto do Botão", name: "text", widget: "string"}
      - {label: "URL (Link de Destino)", name: "url", widget: "string"}
