backend:
  name: github
  repo: jornadablue/jornadablue.github.io # Seu repositório
  branch: main # Seu branch principal

# Esta configuração é para gerenciar um único arquivo com uma lista de botões
collections:
  - name: "links"
    label: "Links da Página Principal"
    files:
      - label: "Botões de Links"
        name: "buttons"
        file: "data/buttons.json" # O arquivo de dados que será gerenciado
        fields:
          - label: "Lista de Botões"
            name: "buttons"
            widget: "list"
            fields:
              - {label: "Texto do Botão", name: "text", widget: "string"}
              - {label: "URL (Link de Destino)", name: "url", widget: "string"}
