backend:
  name: github
  repo: jornadablue/jornadablue.github.io
  branch: main

collections:
  - name: "links"
    label: "Links da Página Principal"
    files:
      - label: "Botões de Links"
        name: "buttons"
        file: "data/buttons.json"
        fields:
          - label: "Lista de Botões"
            name: "buttons"
            widget: "list"
            fields:
              - label: "Texto do Botão"
                name: "text"
                widget: "string"
              - label: "URL (Link de Destino)"
                name: "url"
                widget: "string"
